; ==========================================================
; ModuleID = 'vit_module'
; Generated by VIT Compiler (Phase 3)
; ==========================================================

source_filename = "vit_module.jslik"
target triple = "x86_64-pc-windows-msvc"

@.fmt_num = private unnamed_addr constant [4 x i8] c"%f\0A\00", align 1
@.fmt_str = private unnamed_addr constant [4 x i8] c"%s\0A\00", align 1
@.fmt_bool_true = private unnamed_addr constant [6 x i8] c"true\0A\00", align 1
@.fmt_bool_false = private unnamed_addr constant [7 x i8] c"false\0A\00", align 1
@.str.bounds_panic = private unnamed_addr constant [21 x i8] c"Index out of bounds\0A\00", align 1

%struct.VitCliConfig = type { i8*, i8*, i8*, i8* }
@.str.0 = private unnamed_addr constant [58 x i8] c"=========================================================\00", align 1
@.str.1 = private unnamed_addr constant [19 x i8] c" 🛠 `vit create \00", align 1
@.str.2 = private unnamed_addr constant [24 x i8] c"` Scaffolding Generator\00", align 1
@.str.3 = private unnamed_addr constant [58 x i8] c"=========================================================\00", align 1
@.str.4 = private unnamed_addr constant [41 x i8] c"  [+] Creating directory structure for: \00", align 1
@.str.5 = private unnamed_addr constant [50 x i8] c"  [+] Initializing vit.json project configuration\00", align 1
@.str.6 = private unnamed_addr constant [47 x i8] c"  [+] Generated src/main.vit (Vito Web Engine)\00", align 1
@.str.7 = private unnamed_addr constant [46 x i8] c"  [+] Scaffolding Monorepo packages/ & tests/\00", align 1
@.str.8 = private unnamed_addr constant [15 x i8] c"  [+] Project \00", align 1
@.str.9 = private unnamed_addr constant [23 x i8] c" created successfully!\00", align 1
@.str.10 = private unnamed_addr constant [58 x i8] c"=========================================================\00", align 1
@.str.11 = private unnamed_addr constant [38 x i8] c" ⚡ `vit dev` HMR Auto-Reload Server\00", align 1
@.str.12 = private unnamed_addr constant [58 x i8] c"=========================================================\00", align 1
@.str.13 = private unnamed_addr constant [50 x i8] c"  [Watcher] Monitoring directory: src/, packages/\00", align 1
@.str.14 = private unnamed_addr constant [43 x i8] c"  [HMR] Server active on http://127.0.0.1:\00", align 1
@.str.15 = private unnamed_addr constant [56 x i8] c"  [HMR] Ready for instant code updates without restart!\00", align 1
@.str.16 = private unnamed_addr constant [58 x i8] c"=========================================================\00", align 1
@.str.17 = private unnamed_addr constant [57 x i8] c" 📦 `vit build --binary` Standalone Executable Bundler\00", align 1
@.str.18 = private unnamed_addr constant [58 x i8] c"=========================================================\00", align 1
@.str.19 = private unnamed_addr constant [19 x i8] c"  [1/3] Compiling \00", align 1
@.str.20 = private unnamed_addr constant [29 x i8] c" with LLVM Native Backend...\00", align 1
@.str.21 = private unnamed_addr constant [54 x i8] c"  [2/3] Bundling Vito Web Engine & dependency tree...\00", align 1
@.str.22 = private unnamed_addr constant [44 x i8] c"  [3/3] Emitting single native executable: \00", align 1
@.str.23 = private unnamed_addr constant [67 x i8] c"  [SUCCESS] Binary size: 4.2 MB (Zero external runtime dependency)\00", align 1
@.str.24 = private unnamed_addr constant [23 x i8] c"my-vito-enterprise-app\00", align 1
@.str.25 = private unnamed_addr constant [9 x i8] c"rest-api\00", align 1
@.str.26 = private unnamed_addr constant [1 x i8] c"\00", align 1
@.str.27 = private unnamed_addr constant [1 x i8] c"\00", align 1
@.str.28 = private unnamed_addr constant [13 x i8] c"src/main.vit\00", align 1
@.str.29 = private unnamed_addr constant [27 x i8] c"my-vito-enterprise-app.exe\00", align 1

declare i32 @printf(i8*, ...)
declare i32 @sprintf(i8*, i8*, ...)
declare i8* @malloc(i64)
declare void @free(i8*)
declare i64 @strlen(i8*)
declare i32 @strcmp(i8*, i8*)
declare i8* @strcpy(i8*, i8*)
declare i8* @strcat(i8*, i8*)
declare void @exit(i32)
declare void @__vit_init_args(i32, i8**)

declare i8* @vit_thread_spawn(i8*, i8*)
declare void @vit_thread_join(i8*)
declare void @vit_thread_detach(i8*)
declare i8* @vit_channel_create()
declare void @vit_channel_send(i8*, double)
declare double @vit_channel_receive(i8*)
declare void @vit_channel_free(i8*)
declare i8* @vit_promise_create()
declare void @vit_promise_resolve(i8*, double)
declare double @vit_promise_await(i8*)
declare void @vit_promise_free(i8*)
declare void @vit_task_spawn(i8*, i8*)

define void @__vit_panic(i8* %msg) {
  %fmt = getelementptr inbounds [4 x i8], [4 x i8]* @.fmt_str, i64 0, i64 0
  %call = call i32 (i8*, ...) @printf(i8* %fmt, i8* %msg)
  call void @exit(i32 1)
  unreachable
}

define i1 @vitCreateProject(i8* %appName, i8* %template) {
entry:
  %appName.addr = alloca i8*, align 8
  store i8* %appName, i8** %appName.addr, align 8
  %template.addr = alloca i8*, align 8
  store i8* %template, i8** %template.addr, align 8
  %t0 = getelementptr inbounds [58 x i8], [58 x i8]* @.str.0, i64 0, i64 0
  %t1 = getelementptr inbounds [4 x i8], [4 x i8]* @.fmt_str, i64 0, i64 0
  %t2 = call i32 (i8*, ...) @printf(i8* %t1, i8* %t0)
  %t3 = getelementptr inbounds [19 x i8], [19 x i8]* @.str.1, i64 0, i64 0
  %t4 = load i8*, i8** %appName.addr, align 8
  %t6 = call i64 @strlen(i8* %t3)
  %t7 = call i64 @strlen(i8* %t4)
  %t8 = add i64 %t6, %t7
  %t9 = add i64 %t8, 1
  %t10 = call i8* @malloc(i64 %t9)
  %t11 = call i8* @strcpy(i8* %t10, i8* %t3)
  %t12 = call i8* @strcat(i8* %t10, i8* %t4)
  %t13 = getelementptr inbounds [24 x i8], [24 x i8]* @.str.2, i64 0, i64 0
  %t15 = call i64 @strlen(i8* %t10)
  %t16 = call i64 @strlen(i8* %t13)
  %t17 = add i64 %t15, %t16
  %t18 = add i64 %t17, 1
  %t19 = call i8* @malloc(i64 %t18)
  %t20 = call i8* @strcpy(i8* %t19, i8* %t10)
  %t21 = call i8* @strcat(i8* %t19, i8* %t13)
  %t22 = getelementptr inbounds [4 x i8], [4 x i8]* @.fmt_str, i64 0, i64 0
  %t23 = call i32 (i8*, ...) @printf(i8* %t22, i8* %t19)
  %t24 = getelementptr inbounds [58 x i8], [58 x i8]* @.str.3, i64 0, i64 0
  %t25 = getelementptr inbounds [4 x i8], [4 x i8]* @.fmt_str, i64 0, i64 0
  %t26 = call i32 (i8*, ...) @printf(i8* %t25, i8* %t24)
  %t27 = getelementptr inbounds [41 x i8], [41 x i8]* @.str.4, i64 0, i64 0
  %t28 = load i8*, i8** %appName.addr, align 8
  %t30 = call i64 @strlen(i8* %t27)
  %t31 = call i64 @strlen(i8* %t28)
  %t32 = add i64 %t30, %t31
  %t33 = add i64 %t32, 1
  %t34 = call i8* @malloc(i64 %t33)
  %t35 = call i8* @strcpy(i8* %t34, i8* %t27)
  %t36 = call i8* @strcat(i8* %t34, i8* %t28)
  %t37 = getelementptr inbounds [4 x i8], [4 x i8]* @.fmt_str, i64 0, i64 0
  %t38 = call i32 (i8*, ...) @printf(i8* %t37, i8* %t34)
  %t39 = getelementptr inbounds [50 x i8], [50 x i8]* @.str.5, i64 0, i64 0
  %t40 = getelementptr inbounds [4 x i8], [4 x i8]* @.fmt_str, i64 0, i64 0
  %t41 = call i32 (i8*, ...) @printf(i8* %t40, i8* %t39)
  %t42 = getelementptr inbounds [47 x i8], [47 x i8]* @.str.6, i64 0, i64 0
  %t43 = getelementptr inbounds [4 x i8], [4 x i8]* @.fmt_str, i64 0, i64 0
  %t44 = call i32 (i8*, ...) @printf(i8* %t43, i8* %t42)
  %t45 = getelementptr inbounds [46 x i8], [46 x i8]* @.str.7, i64 0, i64 0
  %t46 = getelementptr inbounds [4 x i8], [4 x i8]* @.fmt_str, i64 0, i64 0
  %t47 = call i32 (i8*, ...) @printf(i8* %t46, i8* %t45)
  %t48 = getelementptr inbounds [15 x i8], [15 x i8]* @.str.8, i64 0, i64 0
  %t49 = load i8*, i8** %appName.addr, align 8
  %t51 = call i64 @strlen(i8* %t48)
  %t52 = call i64 @strlen(i8* %t49)
  %t53 = add i64 %t51, %t52
  %t54 = add i64 %t53, 1
  %t55 = call i8* @malloc(i64 %t54)
  %t56 = call i8* @strcpy(i8* %t55, i8* %t48)
  %t57 = call i8* @strcat(i8* %t55, i8* %t49)
  %t58 = getelementptr inbounds [23 x i8], [23 x i8]* @.str.9, i64 0, i64 0
  %t60 = call i64 @strlen(i8* %t55)
  %t61 = call i64 @strlen(i8* %t58)
  %t62 = add i64 %t60, %t61
  %t63 = add i64 %t62, 1
  %t64 = call i8* @malloc(i64 %t63)
  %t65 = call i8* @strcpy(i8* %t64, i8* %t55)
  %t66 = call i8* @strcat(i8* %t64, i8* %t58)
  %t67 = getelementptr inbounds [4 x i8], [4 x i8]* @.fmt_str, i64 0, i64 0
  %t68 = call i32 (i8*, ...) @printf(i8* %t67, i8* %t64)
  ret i1 true
}

define void @vitDevServer(double %port) {
entry:
  %port.addr = alloca double, align 8
  store double %port, double* %port.addr, align 8
  %t0 = getelementptr inbounds [58 x i8], [58 x i8]* @.str.10, i64 0, i64 0
  %t1 = getelementptr inbounds [4 x i8], [4 x i8]* @.fmt_str, i64 0, i64 0
  %t2 = call i32 (i8*, ...) @printf(i8* %t1, i8* %t0)
  %t3 = getelementptr inbounds [38 x i8], [38 x i8]* @.str.11, i64 0, i64 0
  %t4 = getelementptr inbounds [4 x i8], [4 x i8]* @.fmt_str, i64 0, i64 0
  %t5 = call i32 (i8*, ...) @printf(i8* %t4, i8* %t3)
  %t6 = getelementptr inbounds [58 x i8], [58 x i8]* @.str.12, i64 0, i64 0
  %t7 = getelementptr inbounds [4 x i8], [4 x i8]* @.fmt_str, i64 0, i64 0
  %t8 = call i32 (i8*, ...) @printf(i8* %t7, i8* %t6)
  %t9 = getelementptr inbounds [50 x i8], [50 x i8]* @.str.13, i64 0, i64 0
  %t10 = getelementptr inbounds [4 x i8], [4 x i8]* @.fmt_str, i64 0, i64 0
  %t11 = call i32 (i8*, ...) @printf(i8* %t10, i8* %t9)
  %t12 = getelementptr inbounds [43 x i8], [43 x i8]* @.str.14, i64 0, i64 0
  %t13 = load double, double* %port.addr, align 8
  %t15 = call i8* @malloc(i64 64)
  %t16 = getelementptr inbounds [4 x i8], [4 x i8]* @.fmt_num, i64 0, i64 0
  call i32 (i8*, i8*, ...) @sprintf(i8* %t15, i8* %t16, double %t13)
  %t17 = call i64 @strlen(i8* %t12)
  %t18 = call i64 @strlen(i8* %t15)
  %t19 = add i64 %t17, %t18
  %t20 = add i64 %t19, 1
  %t21 = call i8* @malloc(i64 %t20)
  %t22 = call i8* @strcpy(i8* %t21, i8* %t12)
  %t23 = call i8* @strcat(i8* %t21, i8* %t15)
  %t24 = getelementptr inbounds [4 x i8], [4 x i8]* @.fmt_str, i64 0, i64 0
  %t25 = call i32 (i8*, ...) @printf(i8* %t24, i8* %t21)
  %t26 = getelementptr inbounds [56 x i8], [56 x i8]* @.str.15, i64 0, i64 0
  %t27 = getelementptr inbounds [4 x i8], [4 x i8]* @.fmt_str, i64 0, i64 0
  %t28 = call i32 (i8*, ...) @printf(i8* %t27, i8* %t26)
  ret void
}

define i1 @vitBuildSingleBinary(i8* %sourceFile, i8* %outputBinary) {
entry:
  %sourceFile.addr = alloca i8*, align 8
  store i8* %sourceFile, i8** %sourceFile.addr, align 8
  %outputBinary.addr = alloca i8*, align 8
  store i8* %outputBinary, i8** %outputBinary.addr, align 8
  %t0 = getelementptr inbounds [58 x i8], [58 x i8]* @.str.16, i64 0, i64 0
  %t1 = getelementptr inbounds [4 x i8], [4 x i8]* @.fmt_str, i64 0, i64 0
  %t2 = call i32 (i8*, ...) @printf(i8* %t1, i8* %t0)
  %t3 = getelementptr inbounds [57 x i8], [57 x i8]* @.str.17, i64 0, i64 0
  %t4 = getelementptr inbounds [4 x i8], [4 x i8]* @.fmt_str, i64 0, i64 0
  %t5 = call i32 (i8*, ...) @printf(i8* %t4, i8* %t3)
  %t6 = getelementptr inbounds [58 x i8], [58 x i8]* @.str.18, i64 0, i64 0
  %t7 = getelementptr inbounds [4 x i8], [4 x i8]* @.fmt_str, i64 0, i64 0
  %t8 = call i32 (i8*, ...) @printf(i8* %t7, i8* %t6)
  %t9 = getelementptr inbounds [19 x i8], [19 x i8]* @.str.19, i64 0, i64 0
  %t10 = load i8*, i8** %sourceFile.addr, align 8
  %t12 = call i64 @strlen(i8* %t9)
  %t13 = call i64 @strlen(i8* %t10)
  %t14 = add i64 %t12, %t13
  %t15 = add i64 %t14, 1
  %t16 = call i8* @malloc(i64 %t15)
  %t17 = call i8* @strcpy(i8* %t16, i8* %t9)
  %t18 = call i8* @strcat(i8* %t16, i8* %t10)
  %t19 = getelementptr inbounds [29 x i8], [29 x i8]* @.str.20, i64 0, i64 0
  %t21 = call i64 @strlen(i8* %t16)
  %t22 = call i64 @strlen(i8* %t19)
  %t23 = add i64 %t21, %t22
  %t24 = add i64 %t23, 1
  %t25 = call i8* @malloc(i64 %t24)
  %t26 = call i8* @strcpy(i8* %t25, i8* %t16)
  %t27 = call i8* @strcat(i8* %t25, i8* %t19)
  %t28 = getelementptr inbounds [4 x i8], [4 x i8]* @.fmt_str, i64 0, i64 0
  %t29 = call i32 (i8*, ...) @printf(i8* %t28, i8* %t25)
  %t30 = getelementptr inbounds [54 x i8], [54 x i8]* @.str.21, i64 0, i64 0
  %t31 = getelementptr inbounds [4 x i8], [4 x i8]* @.fmt_str, i64 0, i64 0
  %t32 = call i32 (i8*, ...) @printf(i8* %t31, i8* %t30)
  %t33 = getelementptr inbounds [44 x i8], [44 x i8]* @.str.22, i64 0, i64 0
  %t34 = load i8*, i8** %outputBinary.addr, align 8
  %t36 = call i64 @strlen(i8* %t33)
  %t37 = call i64 @strlen(i8* %t34)
  %t38 = add i64 %t36, %t37
  %t39 = add i64 %t38, 1
  %t40 = call i8* @malloc(i64 %t39)
  %t41 = call i8* @strcpy(i8* %t40, i8* %t33)
  %t42 = call i8* @strcat(i8* %t40, i8* %t34)
  %t43 = getelementptr inbounds [4 x i8], [4 x i8]* @.fmt_str, i64 0, i64 0
  %t44 = call i32 (i8*, ...) @printf(i8* %t43, i8* %t40)
  %t45 = getelementptr inbounds [67 x i8], [67 x i8]* @.str.23, i64 0, i64 0
  %t46 = getelementptr inbounds [4 x i8], [4 x i8]* @.fmt_str, i64 0, i64 0
  %t47 = call i32 (i8*, ...) @printf(i8* %t46, i8* %t45)
  ret i1 true
}

define i32 @main(i32 %argc, i8** %argv) {
entry:
  call void @__vit_init_args(i32 %argc, i8** %argv)
  %t0 = getelementptr inbounds [23 x i8], [23 x i8]* @.str.24, i64 0, i64 0
  %t1 = getelementptr inbounds [9 x i8], [9 x i8]* @.str.25, i64 0, i64 0
  %t2 = call i1 @vitCreateProject(i8* %t0, i8* %t1)
  %t3 = getelementptr inbounds [1 x i8], [1 x i8]* @.str.26, i64 0, i64 0
  %t4 = getelementptr inbounds [4 x i8], [4 x i8]* @.fmt_str, i64 0, i64 0
  %t5 = call i32 (i8*, ...) @printf(i8* %t4, i8* %t3)
  call void @vitDevServer(double 3000.0)
  %t6 = getelementptr inbounds [1 x i8], [1 x i8]* @.str.27, i64 0, i64 0
  %t7 = getelementptr inbounds [4 x i8], [4 x i8]* @.fmt_str, i64 0, i64 0
  %t8 = call i32 (i8*, ...) @printf(i8* %t7, i8* %t6)
  %t9 = getelementptr inbounds [13 x i8], [13 x i8]* @.str.28, i64 0, i64 0
  %t10 = getelementptr inbounds [27 x i8], [27 x i8]* @.str.29, i64 0, i64 0
  %t11 = call i1 @vitBuildSingleBinary(i8* %t9, i8* %t10)
  %t12 = fptosi double 0.0 to i32
  ret i32 %t12
}

